#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i 's/user  *www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-available/default
service apache2 stop 2>/dev/null
pkill apache2 2>/dev/null
pkill nginx 2>/dev/null
chmod 755 /etc/nginx/nginx.conf
chmod 755 /var/log/nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
nginx
