#!/usr/bin/env bash
# Configures a new Ubuntu machine's Nginx to include a custom
# HTTP response header X-Served-By with the server's hostname

apt-get update -y
apt-get install -y nginx

sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default

service nginx restart