#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

# Update and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy frontend and backend
# We use 'tee' without '-a' to overwrite the file and prevent duplicates if the script is run multiple times
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend dianah_frontend
    bind *:80
    default_backend dianah_backend

backend dianah_backend
    balance roundrobin
    server 7009-web-01 52.90.67.39:80 check
    server 7009-web-02 44.208.165.54:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart