#!/usr/bin/env bash
# Fix Nginx to listen on port 80 on all active IPv4 IPs
sed -i 's/listen [0-9]*\b/listen 80/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:[0-9]*/listen [::]:80/' /etc/nginx/sites-enabled/default
service nginx start
