#!/usr/bin/env bash
# Fix Nginx to listen on port 80 on all active IPv4 IPs
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server;/listen [::]:80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
