#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page
# the redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx ufw
sudo ufw allow 'Nginx HTTP'

# Use sed to add the redirection rule
# /server_name _;/ matches the line, 'a' appends after it
sudo sed -i '/server_name _;/a \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
