#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page
# and a custom 404 page contains the string "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get -y install nginx

# Setup /redirect_me
sudo sed -i '/server_name _;/a \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup custom 404 page content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Setup custom 404 error page directive
sudo sed -i '/server_name _;/a \ \terror_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
